# Generated by Django 6.0 on 2026-02-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_time',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='duration',
            field=models.CharField(default='3 Days', max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='highlights',
            field=models.TextField(default='Beautiful destination'),
        ),
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
