# Generated by Django 6.0 on 2026-02-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelworld', '0002_destination_best_time_destination_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='highlights',
            field=models.TextField(default='Beautiful destination', max_length=1000),
        ),
    ]
